screener/urls.py
from django.urls import path
from . import views


app_name = 'screener'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    
    # page contains portfolio info
    path('portfolio/', views.portfolio, name='portfolio'),
    
    # page contains list of user wallets
    path('manage_portfolio/', views.manage_portfolio, name='manage_portfolio'),
    
    # page contains wallet addresses
    path('user_wallets/addresses/<int:wallet_id>/', views.addresses, name='addresses'),
    
    # info about wallet
    path('user_wallets/user_wallet_info/<int:wallet_id>/', views.user_wallet_info, name='user_wallet_info'),
    
    # page contains address info
    path('address_info/<int:address_id>/', views.address_info, name='address_info'),
    
    # edit portfolio page
    path('edit_portfolio/', views.edit_portfolio, name='edit_portfolio'),
    
    # add wallet
    path('manage_portfolio/add_wallet/', views.add_wallet, name='add_wallet'),
    
    # delete user wallet
    path('manage_portfolio/del_wallet/<int:wallet_id>/', views.del_wallet, name='del_wallet'),
    
    # add address
    path('manage_portfolio/add_address/<int:wallet_id>/', views.add_address, name='add_address'),
    
    # delete address
    path('manage_portfolio/del_address/<int:address_id>/', views.del_address, name='del_address'),
    
    # page contains update links
    path('update/', views.update, name='update'),
    
    # update list of all chain and all token price
    path('update_data/', views.update_data, name='update_data'),
    
    # update token amount for all user addresses
    path('update_amount_data/', views.update_amount_data, name='update_amount_data'),
    
    # create chain and price table
    path('table_fill/', views.table_fill, name='table_fill'),
    
    # page contains site info
    path('about/', views.about, name='about'),
    
    # page contains ours contacts
    path('contacts/', views.contacts, name='contacts'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

wallets_screen/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('screener.urls')),
    path('users/', include('users.urls')),
] + debug_toolbar_urls()

screener/models.py
from django.db import models
from django.contrib.auth.models import User


class Wallet(models.Model):
    wallet_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    wallet_name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.wallet_name


class TokenInfo(models.Model):
    chain = models.CharField(max_length=20, unique=True, null=True, blank=True)
    current_price = models.FloatField(max_length=10, null=True, blank=True)


class Address(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    staked = models.FloatField(max_length=30, null=True, default='0', blank=True)
    available = models.FloatField(max_length=30, null=True, default='0', blank=True)
    reward = models.FloatField(max_length=30, null=True, default='0', blank=True)
    
    def __str__(self):
        return self.address

screener/forms.py
from django import forms
from .models import Wallet, Address
from django.core.exceptions import ValidationError
from screener.services.config_parse import list_of_support_chain


class WalletForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = ['wallet_name']
        label = {'wallet_name': ''}


class AdressForm(forms.ModelForm):
    
    def clean_address(self):
        cleaned_data = super().clean()
        input_address = cleaned_data.get('address')

        if input_address[:-39] not in list_of_support_chain:
            raise ValidationError('Unsupported chain or incorrect address!')
            
            # try:
            # address = Address.objects.get(address=input_address)
            # wallet_id = address.wallet_id
            # wallet = Wallet.objects.get(pk=wallet_id)
            # addresses = wallet.address_set.all()
            # if any(addr for addr in addresses if str(addr) == input_address):
            #     raise ValidationError('Address is duplicate in this wallet!')
            #
            # except Address.DoesNotExist:
        return cleaned_data.get('address')
    
    class Meta:
        model = Address
        fields = ['address']
        label = {'address': ''}

screener/views.py
from django.shortcuts import render, redirect
from .models import Wallet, Address
from .forms import WalletForm, AdressForm
from .services.update_data import update_amount, update_token_info_table
from .services.download_data_from_db import wallet_data_db, address_data_db, portfolio_data_db
from .services.create_chain_table import get_table_fill


# Create your views here.


def index(request):
    """Home page"""
    return render(request, 'screener/index.html')


def portfolio(request):
    data = portfolio_data_db(request.user)
    context = {
        'data': data[0],
        'sum': data[0]['portfolio_sum'],
        'amount': data[1]
        
    }
    return render(request, 'screener/show_portfolio.html', context)


def wallets(request):
    """page contains list of all wallets"""
    wallets = Wallet.objects.all()
    context = {'wallets': wallets}
    return render(request, 'screener/wallets.html', context)


def manage_portfolio(request):
    """page contains list of user wallets"""
    context = {
        'user_wallets': Wallet.objects.filter(wallet_owner=request.user).select_related('wallet_owner')
    }
    return render(request, 'screener/manage_portfolio.html', context)


def user_wallet_info(request, wallet_id):
    context = {
        'wallet_data': wallet_data_db(wallet_id),
    }
    return render(request, 'screener/user_wallet_info.html', context)


def add_wallet(request):
    """Add wallet to user portfolio"""
    if request.method != 'POST':
        form = WalletForm()
    else:
        form = WalletForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.wallet_owner = request.user
            form.save()
            return redirect('screener:user_wallets')
    context = {'form': form}
    return render(request, 'screener/add_wallet.html', context)


def edit_portfolio(request, wallet_id):
    return render(request, 'screener/edit_portfolio.html')


def del_wallet(request, wallet_id):
    """Del user wallet"""
    wallet = Wallet.objects.get(id=wallet_id)
    wallet.delete()
    return redirect('screener:user_wallets')


def addresses(request, wallet_id):
    """page contains wallet addresses"""
    wallet = Wallet.objects.get(id=wallet_id)
    addresses = wallet.address_set.all()
    if addresses:
        context = {
            'addresses': addresses,
            'wallet': wallet
        }
    else:
        text = 'No added addresses'
        context = {
            'text': text,
            'wallet': wallet
        }
    return render(request, 'screener/addresses.html', context)


def update(request):
    return render(request, 'screener/update.html')


def update_amount_data(request):
    """ update token amount for all user addresses """
    context = {
        'text': update_amount(),
    }
    return render(request, 'screener/index.html', context)


def update_data(request):
    """ Update list of chain and price for all supported token """
    context = {
        'text': update_token_info_table(),
        'text': update_token_info_table(),
    }
    return render(request, 'screener/index.html', context)


def table_fill(request):
    context = {
        'text': get_table_fill()
    }
    return render(request, 'screener/index.html', context)


def address_info(request, address_id):
    address = Address.objects.get(id=address_id)
    context = {
        'data': address_data_db(address)
    }
    return render(request, 'screener/address_info.html', context)


def add_address(request, wallet_id):
    """Add address to user wallet"""
    wallet = Wallet.objects.get(id=wallet_id)
    if request.method != 'POST':
        form = AdressForm()
    else:
        form = AdressForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.wallet = wallet
            form.save()
            return redirect('screener:addresses', wallet_id=wallet.id)
    context = {
        'form': form,
        'wallet': wallet,
    }
    return render(request, 'screener/add_address.html', context)


def del_address(request, address_id):
    """Delete address from user wallet"""
    address = Address.objects.get(id=address_id)
    wallet_id = address.wallet_id
    address.delete()
    return redirect('screener:addresses', wallet_id)


def about(request):
    """page contains site info"""
    return render(request, 'screener/about.html')


def contacts(request):
    """page contains ours contacts"""
    return render(request, 'screener/contacts.html')
    

screener/templates/screener/about.html
{% extends 'base.html' %}
{% block content%}
<p>ABOUT SITE</p>
{% endblock content%}

screener/templates/screener/add_address.html
{% extends 'base.html' %}

{% block content%}
  <p>Add new address in {{wallet}}-wallet:</p>
  <form action="{% url 'screener:add_address' wallet.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add new address in {{ wallet }}-wallet</button>
  </form>
{% endblock content%}

screener/templates/screener/add_wallet.html
{% extends 'base.html' %}

{% block content%}
  <p>Add new wallet:</p>
  <form action="{% url 'screener:add_wallet' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add wallet</button>
  </form>
{% endblock content%}

screener/templates/screener/address_info.html
{% extends 'base.html' %}

{% block content %}
  <p>
      address: {{ address }}
  </p>
  <ul>
      <p>chain : {{ data.chain }}</p>
      <p>current price: {{ data.price }}</p>
      <p>staked: {{ data.staked }}</p>
      <p>available: {{ data.available }}</p>
      <p>reward: {{ data.reward }}</p>
      <p> all token: {{ data.all }}</p>
      <p> all token price: {{ data.coast }}</p>
  </ul>
{% endblock content%}

screener/templates/screener/addresses.html
{% extends 'base.html' %}

{% block content %}
  <p>{{wallet}}-wallet addresses:</p>
  <p>{{text}}</p>
    {% for address in addresses %}
      <li>
        {{ address }} <a href="{% url 'screener:address_info' address.id %}">address info</a>
        <form method="post" action="{% url 'screener:del_address' address.id %}">
          {% csrf_token %}
          <button onclick="return confirm('Delete {{address}}. Are you sure?')" type="submit">
            Delete
          </button>
        </form>
      </li>
    {% endfor%}
  <ul>
    <p>{{ token_info }}</p>
  </ul>
  <a href="{% url 'screener:add_address' wallet.id %}">Add new address</a>
{% endblock content%}

screener/templates/screener/contacts.html
{% extends 'base.html' %}
{% block content%}
<p>OURS CONTACTS</p>
{% endblock content%}

screener/templates/screener/edit_portfolio.html
{% extends 'base.html' %}
{% block content%}
  <p>WALLETS</p>
  {% for wallet in user_wallets %}
    <li>
      <a href="{% url 'screener:addresses' wallet.id %}">{{ wallet }}</a>
    </li>
  {% endfor %}
  <a href="{% url 'screener:add_wallet'%}">Add new wallet</a>
{% endblock %}

screener/templates/screener/index.html
{% extends 'base.html' %}
{% block content%}
<p>MAIN PAGE</p>
<p><a href="{% url 'screener:update' %}">Update page</a></p>
<p>{{ text }}</p>
{% endblock content%}

screener/templates/screener/manage_portfolio.html
{% extends 'base.html' %}
{% block content%}
  <p>WALLETS</p>
  {% for wallet in user_wallets %}
      <a href="{% url 'screener:addresses' wallet.id %}">{{ wallet }}</a> |
      <a href="{% url 'screener:user_wallet_info' wallet.id %}">wallet info</a>
      <a href="{% url 'screener:del_wallet' wallet.id %}" class="ui button red"></a>
        <form method="post" action="{% url 'screener:del_wallet' wallet.id %}">
          {% csrf_token %}
          <button onclick="return confirm('Delete {{wallet}}. Are you sure?')" type="submit">
            Delete
          </button>
        </form>
  {% endfor %}
  <a href="{% url 'screener:add_wallet' %}">Add wallet</a>
{% endblock content%}

screener/templates/screener/show_portfolio.html
{% extends 'base.html' %}
{% block content%}
All wallets in your portfolio
{% for key, value in data.items %}
  <ul>
    {{ key }} - $ {{ value.wallet_sum }}
  </ul>
<!--    {% for k, v in value.items %}-->
<!--    <ul>-->
<!--      {% for i, j in v.items %}-->
<!--        {{ i }}: {{ j }}-->
<!--      {% endfor %}-->
<!--    </ul>-->
<!--    {% endfor %}-->
{% endfor %}

All amout in your portfolio $ {{ sum }}
  <p> </p>
  {% for key, value in amount.items %}
    <li>
      {{key}}:
      {% for i, j in value.items %}
      {{ i }}
      {{ j }}
    {% endfor %}
    </li>
    <ul>
<!--    {% for i, j in value.items %}-->
<!--      {{ i }}-->
<!--      {{ j }}-->
<!--    {% endfor %}-->
    </ul>
  {% endfor %}
{% endblock content%}

screener/templates/screener/update.html
{% extends 'base.html' %}
{% block content%}
<p>UPDATE PAGE</p>
<p><a href="{% url 'screener:update_data' %}">Update price for all chains</a></p>
<p><a href="{% url 'screener:update_amount_data' %}">Update amount data</a></p>
<p><a href="{% url 'screener:table_fill' %}">Fill chain table</a></p>
<p>{{ text }}</p>
{% endblock content%}

screener/templates/screener/user_wallet_info.html
{% extends 'base.html' %}
{% block content%}
  <p>INFO about {{ wallet_name }} - wallet</p>
    {% for key, value in wallet_data.items %}
      <ul>
        {{key}}
        {{value}}
      </ul>
    {% endfor %}
{% endblock content%}

screener/templates/screener/user_wallets.html
{% extends 'base.html' %}
{% block content%}
  <p>WALLETS</p>
  {% for wallet in user_wallets %}
      <a href="{% url 'screener:addresses' wallet.id %}">{{ wallet }}</a>
      <a href="{% url 'screener:user_wallet_info' wallet.id %}">wallet info</a>
      <a href="{% url 'screener:del_wallet' wallet.id %}" class="ui button red"></a>
        <form method="post" action="{% url 'screener:del_wallet' wallet.id %}">
          {% csrf_token %}
          <button onclick="return confirm('Delete {{wallet}}. Are you sure?')" type="submit">
            Delete
          </button>
        </form>
  {% endfor %}
  <a href="{% url 'screener:add_wallet' %}">Add wallet</a>
{% endblock content%}

screener/templates/screener/wallets.html
{% extends 'base.html' %}

{% block content%}
  <p>WALLETS</p>
  {% for wallet in wallets %}
    <li>
      <a href="{% url 'screener:addresses' wallet.id %}">{{ wallet }}</a>
    </li>
  {% endfor %}
  <a href="{% url 'main:add_wallet '%}">Add new wallet</a>
{% endblock content%}