screener/urls.py
from django.urls import path
from . import views


app_name = 'screener'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    
    # page contains portfolio info
    path('portfolio/', views.portfolio, name='portfolio'),
    
    # page contains list of user wallets
    path('manage_portfolio/', views.manage_portfolio, name='manage_portfolio'),
    
    # page contains wallet addresses
    path('user_wallets/addresses/<int:wallet_id>/', views.addresses, name='addresses'),
    
    # info about wallet
    path('user_wallets/user_wallet_info/<int:wallet_id>/', views.user_wallet_info, name='user_wallet_info'),
    
    # page contains address info
    path('address_info/<int:address_id>/', views.address_info, name='address_info'),
    
    # edit portfolio page
    path('edit_portfolio/', views.edit_portfolio, name='edit_portfolio'),
    
    # add wallet
    path('manage_portfolio/add_wallet/', views.add_wallet, name='add_wallet'),
    
    # delete user wallet
    path('manage_portfolio/del_wallet/<int:wallet_id>/', views.del_wallet, name='del_wallet'),
    
    # add address
    path('manage_portfolio/add_address/<int:wallet_id>/', views.add_address, name='add_address'),
    
    # delete address
    path('manage_portfolio/del_address/<int:address_id>/', views.del_address, name='del_address'),
    
    # page contains update links
    path('update/', views.update, name='update'),
    
    # update list of all chain and all token price
    path('update_data/', views.update_data, name='update_data'),
    
    # update token amount for all user addresses
    path('update_amount_data/', views.update_amount_data, name='update_amount_data'),
    
    # create chain and price table
    path('table_fill/', views.table_fill, name='table_fill'),
    
    # page contains site info
    path('about/', views.about, name='about'),
    
    # page contains ours contacts
    path('contacts/', views.contacts, name='contacts'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

wallets_screen/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('screener.urls')),
    path('users/', include('users.urls')),
] + debug_toolbar_urls()

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
  Hello, {{ user.username }}
  <form method="post" action="{% url 'users:logout' %}">
      {% csrf_token %}
      <button name="submit">LOG OUT</button>
  </form>
  <p>
    <a href="{% url 'screener:index' %}">Main page</a> |
    <a href="{% url 'screener:portfolio' %}">Your portfolio</a> |
    <a href="{% url 'screener:manage_portfolio' %}">Manage portfolio</a> |
    <a href="{% url 'screener:about' %}">About</a> |
    <a href="{% url 'screener:contacts' %}">Ours contacts</a>

  </p>
{% else %}
  <a href="{% url 'users:login' %}">SIGN IN</a>
{% endif %}
{% block content %}
{% endblock content%}
</body>
</html>